// ---------------------------------------------------------------------------
// US State Abbreviation Map
// ---------------------------------------------------------------------------

export const US_STATE_MAP: Record<string, string> = {
  alabama: "AL",
  alaska: "AK",
  arizona: "AZ",
  arkansas: "AR",
  california: "CA",
  colorado: "CO",
  connecticut: "CT",
  delaware: "DE",
  florida: "FL",
  georgia: "GA",
  hawaii: "HI",
  idaho: "ID",
  illinois: "IL",
  indiana: "IN",
  iowa: "IA",
  kansas: "KS",
  kentucky: "KY",
  louisiana: "LA",
  maine: "ME",
  maryland: "MD",
  massachusetts: "MA",
  michigan: "MI",
  minnesota: "MN",
  mississippi: "MS",
  missouri: "MO",
  montana: "MT",
  nebraska: "NE",
  nevada: "NV",
  "new hampshire": "NH",
  "new jersey": "NJ",
  "new mexico": "NM",
  "new york": "NY",
  "north carolina": "NC",
  "north dakota": "ND",
  ohio: "OH",
  oklahoma: "OK",
  oregon: "OR",
  pennsylvania: "PA",
  "rhode island": "RI",
  "south carolina": "SC",
  "south dakota": "SD",
  tennessee: "TN",
  texas: "TX",
  utah: "UT",
  vermont: "VT",
  virginia: "VA",
  washington: "WA",
  "west virginia": "WV",
  wisconsin: "WI",
  wyoming: "WY",
  "district of columbia": "DC",
  // Common shorthand variants
  calif: "CA",
  cali: "CA",
  tex: "TX",
  penn: "PA",
  mass: "MA",
  conn: "CT",
  wash: "WA",
  minn: "MN",
  wisc: "WI",
  tenn: "TN",
  okla: "OK",
  ore: "OR",
  ariz: "AZ",
  colo: "CO",
  nev: "NV",
  wis: "WI",
  mich: "MI",
};

// ---------------------------------------------------------------------------
// Column Alias Dictionary — maps common CSV header names to ProspectInput keys
// ---------------------------------------------------------------------------
// "__contact_name" is a special pseudo-field: single name columns get split
// into contact_first_name + contact_last_name during normalization.

export const COLUMN_ALIASES: Record<string, string[]> = {
  business_name: [
    "business name",
    "company",
    "company name",
    "business",
    "store name",
    "organization",
    "org",
    "account name",
    "account",
    "dba",
    "doing business as",
    "firm",
    "retailer",
    "shop name",
  ],
  contact_first_name: [
    "first name",
    "first",
    "fname",
    "given name",
    "contact first",
    "contact first name",
  ],
  contact_last_name: [
    "last name",
    "last",
    "lname",
    "surname",
    "family name",
    "contact last",
    "contact last name",
  ],
  email: [
    "email",
    "e-mail",
    "email address",
    "contact email",
    "work email",
    "email addr",
  ],
  phone: [
    "phone",
    "phone number",
    "telephone",
    "tel",
    "mobile",
    "cell",
    "contact phone",
    "work phone",
    "phone #",
    "phone no",
  ],
  website: [
    "website",
    "url",
    "web",
    "site",
    "homepage",
    "domain",
    "web address",
    "website url",
  ],
  address: [
    "address",
    "street",
    "street address",
    "address line 1",
    "addr",
    "address1",
  ],
  city: ["city", "town"],
  state: ["state", "province", "region", "st"],
  zip: [
    "zip",
    "zipcode",
    "zip code",
    "postal code",
    "postal",
    "postcode",
    "zip/postal",
  ],
  store_type: [
    "store type",
    "type",
    "category",
    "business type",
    "industry",
    "vertical",
    "segment",
  ],
  pipeline_stage: [
    "stage",
    "pipeline stage",
    "status",
    "lead status",
    "prospect stage",
  ],
  source: [
    "source",
    "lead source",
    "how found",
    "origin",
    "channel",
    "referral source",
  ],
  estimated_monthly_volume: [
    "volume",
    "monthly volume",
    "est volume",
    "revenue",
    "monthly revenue",
    "estimated revenue",
    "monthly sales",
  ],
  notes: ["notes", "comments", "description", "memo", "remarks", "note"],
  assigned_to: [
    "assigned to",
    "owner",
    "rep",
    "sales rep",
    "assignee",
    "account owner",
  ],
  __contact_name: [
    "contact name",
    "full name",
    "name",
    "contact",
    "person",
    "contact person",
  ],
};

// ---------------------------------------------------------------------------
// Mappable Fields — the ProspectInput keys users can map CSV columns to
// ---------------------------------------------------------------------------

export const MAPPABLE_FIELDS: {
  key: string;
  label: string;
  required: boolean;
}[] = [
  { key: "business_name", label: "Business Name", required: true },
  { key: "contact_first_name", label: "First Name", required: false },
  { key: "contact_last_name", label: "Last Name", required: false },
  { key: "__contact_name", label: "Full Contact Name", required: false },
  { key: "email", label: "Email", required: false },
  { key: "phone", label: "Phone", required: false },
  { key: "website", label: "Website", required: false },
  { key: "address", label: "Address", required: false },
  { key: "city", label: "City", required: false },
  { key: "state", label: "State", required: false },
  { key: "zip", label: "ZIP", required: false },
  { key: "store_type", label: "Store Type", required: false },
  { key: "pipeline_stage", label: "Pipeline Stage", required: false },
  { key: "assigned_to", label: "Assigned To", required: false },
  { key: "source", label: "Source", required: false },
  { key: "estimated_monthly_volume", label: "Est. Monthly Volume", required: false },
  { key: "notes", label: "Notes", required: false },
];
